---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talk
  labels:
    exp: "true"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: talk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: talk
    spec:
      containers:
        - image: thapakazi/talk:latest
          imagePullPolicy: Always
          name: talk
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: talk
  labels:
    exp: "true"
  annotations:
spec:
  ports:
    - name: backend
      port: 80
      targetPort: 3000
  type: ClusterIP
  selector:
    app: talk

---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: talk
#   annotations:
#     kubernetes.io/ingress.class: traefik
# spec:
#   rules:
#   - host: talk.myapp.io
#     http:
#       paths:
#       - path: /
#         backend:
#           serviceName: talk
#           servicePort: 80

