---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: talk
  labels:
    exp: true

spec:
  replicas: 2
  selector:
    matchLabels:
      app: talk
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: talk
    spec:
      containers:
        - image: thapakazi/talk:latest
          imagePullPolicy: Always
          name: talk
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: talk

---
apiVersion: v1
kind: Service
metadata:
  name: talk
  labels:
    exp: true
  annotations:
spec:
  ports:
    - name: backend
      port: 80
      targetPort: 3000
  type: CulsterIp
  selector:
    app: talk
