name: Deploy to server

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: thapakazi/talk
        tags: latest

    - name: Install civo
      uses: civo/action-civo@master
      with:
        token: ${{ secrets.CIVO_TOKEN }}

    - name: Get kubeconfig
      run: civo kubernetes config ${{ secrets.CLUSTER_NAME }} -s -p /tmp/kube.config

    - name: Install kubectl
      run: |
        sudo apt-get install kubectl

    - name: Deploy new release
      run: |
        export KUBECONFIG=/tmp/kube.config
        kubectl apply -f deploy/deployment.yml -n talk
        kubectl rollout status deploy/talk -n talk
